# Generated by Django 4.0.1 on 2022-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errorcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcode',
            name='slug',
            field=models.CharField(default='', max_length=20, verbose_name='Error Slug'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Error Code'),
        ),
    ]
