# Generated by Django 4.0.1 on 2022-01-08 12:29

from django.db import migrations

def create_data(apps, schema_editor):
    Errorcode = apps.get_model('errorcode', 'Errorcode')
    Errorcode(code="000-003", slug="server_error").save()


class Migration(migrations.Migration):

    dependencies = [
        ('errorcode', '0002_errorcode_slug_alter_errorcode_code'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]


